include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.gform.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - unawaited_futures
