name: github
description: "Simple GitHub client app."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  go_router: ^14.2.0
  material_symbols_icons: ^4.2762.0
  flex_color_scheme: ^7.3.1
  flutter_hooks: ^0.20.5
  retrofit: ^4.1.0
  dio: ^5.4.3+1
  collection: ^1.18.0
  hooks_riverpod: ^2.5.1
  drift: ^2.18.0
  path: ^1.9.0
  path_provider: ^2.1.3
  sqlite3_flutter_libs: ^0.5.24
  sqlite3: ^2.4.3
  url_launcher: ^6.3.0
  dynamic_color: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  go_router_builder: ^2.7.0
  retrofit_generator: ^8.1.0
  drift_dev: ^2.18.0
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true
  generate: true
