// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'repository.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$RepositoryItemImpl _$$RepositoryItemImplFromJson(Map<String, dynamic> json) =>
    _$RepositoryItemImpl(
      id: (json['id'] as num).toInt(),
      nodeId: json['node_id'] as String,
      name: json['name'] as String,
      fullName: json['full_name'] as String,
      owner: json['owner'] == null
          ? null
          : SimpleUser.fromJson(json['owner'] as Map<String, dynamic>),
      private: json['private'] as bool,
      htmlUrl: Uri.parse(json['html_url'] as String),
      description: json['description'] as String?,
      fork: json['fork'] as bool,
      url: Uri.parse(json['url'] as String),
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: DateTime.parse(json['updated_at'] as String),
      pushedAt: json['pushed_at'] == null
          ? null
          : DateTime.parse(json['pushed_at'] as String),
      homepage: json['homepage'] == null
          ? null
          : Uri.parse(json['homepage'] as String),
      size: (json['size'] as num).toInt(),
      stargazersCount: (json['stargazers_count'] as num).toInt(),
      watchersCount: (json['watchers_count'] as num).toInt(),
      language: json['language'] as String?,
      forksCount: (json['forks_count'] as num).toInt(),
      openIssuesCount: (json['open_issues_count'] as num).toInt(),
      masterBranch: json['master_branch'] as String?,
      defaultBranch: json['default_branch'] as String,
      score: (json['score'] as num).toDouble(),
      forksUrl: Uri.parse(json['forks_url'] as String),
      keysUrl: json['keys_url'] as String,
      collaboratorsUrl: json['collaborators_url'] as String,
      teamsUrl: Uri.parse(json['teams_url'] as String),
      hooksUrl: Uri.parse(json['hooks_url'] as String),
      issueEventsUrl: json['issue_events_url'] as String,
      eventsUrl: Uri.parse(json['events_url'] as String),
      assigneesUrl: json['assignees_url'] as String,
      branchesUrl: json['branches_url'] as String,
      tagsUrl: Uri.parse(json['tags_url'] as String),
      blobsUrl: json['blobs_url'] as String,
      gitTagsUrl: json['git_tags_url'] as String,
      gitRefsUrl: json['git_refs_url'] as String,
      treesUrl: json['trees_url'] as String,
      statusesUrl: json['statuses_url'] as String,
      languagesUrl: Uri.parse(json['languages_url'] as String),
      stargazersUrl: Uri.parse(json['stargazers_url'] as String),
      contributorsUrl: Uri.parse(json['contributors_url'] as String),
      subscribersUrl: Uri.parse(json['subscribers_url'] as String),
      subscriptionUrl: Uri.parse(json['subscription_url'] as String),
      commitsUrl: json['commits_url'] as String,
      gitCommitsUrl: json['git_commits_url'] as String,
      commentsUrl: json['comments_url'] as String,
      issueCommentUrl: json['issue_comment_url'] as String,
      contentsUrl: json['contents_url'] as String,
      compareUrl: json['compare_url'] as String,
      mergesUrl: Uri.parse(json['merges_url'] as String),
      archiveUrl: json['archive_url'] as String,
      downloadsUrl: Uri.parse(json['downloads_url'] as String),
      issuesUrl: json['issues_url'] as String,
      pullsUrl: json['pulls_url'] as String,
      milestonesUrl: json['milestones_url'] as String,
      notificationsUrl: json['notifications_url'] as String,
      labelsUrl: json['labels_url'] as String,
      releasesUrl: json['releases_url'] as String,
      deploymentsUrl: Uri.parse(json['deployments_url'] as String),
      gitUrl: json['git_url'] as String,
      sshUrl: json['ssh_url'] as String,
      cloneUrl: json['clone_url'] as String,
      svnUrl: Uri.parse(json['svn_url'] as String),
      forks: (json['forks'] as num).toInt(),
      openIssues: (json['open_issues'] as num).toInt(),
      watchers: (json['watchers'] as num).toInt(),
      topics:
          (json['topics'] as List<dynamic>?)?.map((e) => e as String).toList(),
      mirrorUrl: json['mirror_url'] == null
          ? null
          : Uri.parse(json['mirror_url'] as String),
      hasIssues: json['has_issues'] as bool,
      hasProjects: json['has_projects'] as bool,
      hasPages: json['has_pages'] as bool,
      hasWiki: json['has_wiki'] as bool,
      hasDownloads: json['has_downloads'] as bool,
      hasDiscussions: json['has_discussions'] as bool?,
      archived: json['archived'] as bool,
      disabled: json['disabled'] as bool,
      visibility: json['visibility'] as String?,
      license: json['license'] == null
          ? null
          : SimpleLicense.fromJson(json['license'] as Map<String, dynamic>),
      permissions: json['permissions'] == null
          ? null
          : RepositoryPermissions.fromJson(
              json['permissions'] as Map<String, dynamic>),
      textMatches: (json['text_matches'] as List<dynamic>?)
          ?.map((e) => TextMatch.fromJson(e as Map<String, dynamic>))
          .toList(),
      tempCloneToken: json['temp_clone_token'] as String?,
      allowMergeCommit: json['allow_merge_commit'] as bool?,
      allowSquashMerge: json['allow_squash_merge'] as bool?,
      allowRebaseMerge: json['allow_rebase_merge'] as bool?,
      allowAutoMerge: json['allow_auto_merge'] as bool?,
      deleteBranchOnMerge: json['delete_branch_on_merge'] as bool?,
      allowForking: json['allow_forking'] as bool?,
      isTemplate: json['is_template'] as bool?,
      webCommitSignoff: json['web_commit_signoff'] as bool?,
    );

Map<String, dynamic> _$$RepositoryItemImplToJson(
        _$RepositoryItemImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'node_id': instance.nodeId,
      'name': instance.name,
      'full_name': instance.fullName,
      'owner': instance.owner,
      'private': instance.private,
      'html_url': instance.htmlUrl.toString(),
      'description': instance.description,
      'fork': instance.fork,
      'url': instance.url.toString(),
      'created_at': instance.createdAt.toIso8601String(),
      'updated_at': instance.updatedAt.toIso8601String(),
      'pushed_at': instance.pushedAt?.toIso8601String(),
      'homepage': instance.homepage?.toString(),
      'size': instance.size,
      'stargazers_count': instance.stargazersCount,
      'watchers_count': instance.watchersCount,
      'language': instance.language,
      'forks_count': instance.forksCount,
      'open_issues_count': instance.openIssuesCount,
      'master_branch': instance.masterBranch,
      'default_branch': instance.defaultBranch,
      'score': instance.score,
      'forks_url': instance.forksUrl.toString(),
      'keys_url': instance.keysUrl,
      'collaborators_url': instance.collaboratorsUrl,
      'teams_url': instance.teamsUrl.toString(),
      'hooks_url': instance.hooksUrl.toString(),
      'issue_events_url': instance.issueEventsUrl,
      'events_url': instance.eventsUrl.toString(),
      'assignees_url': instance.assigneesUrl,
      'branches_url': instance.branchesUrl,
      'tags_url': instance.tagsUrl.toString(),
      'blobs_url': instance.blobsUrl,
      'git_tags_url': instance.gitTagsUrl,
      'git_refs_url': instance.gitRefsUrl,
      'trees_url': instance.treesUrl,
      'statuses_url': instance.statusesUrl,
      'languages_url': instance.languagesUrl.toString(),
      'stargazers_url': instance.stargazersUrl.toString(),
      'contributors_url': instance.contributorsUrl.toString(),
      'subscribers_url': instance.subscribersUrl.toString(),
      'subscription_url': instance.subscriptionUrl.toString(),
      'commits_url': instance.commitsUrl,
      'git_commits_url': instance.gitCommitsUrl,
      'comments_url': instance.commentsUrl,
      'issue_comment_url': instance.issueCommentUrl,
      'contents_url': instance.contentsUrl,
      'compare_url': instance.compareUrl,
      'merges_url': instance.mergesUrl.toString(),
      'archive_url': instance.archiveUrl,
      'downloads_url': instance.downloadsUrl.toString(),
      'issues_url': instance.issuesUrl,
      'pulls_url': instance.pullsUrl,
      'milestones_url': instance.milestonesUrl,
      'notifications_url': instance.notificationsUrl,
      'labels_url': instance.labelsUrl,
      'releases_url': instance.releasesUrl,
      'deployments_url': instance.deploymentsUrl.toString(),
      'git_url': instance.gitUrl,
      'ssh_url': instance.sshUrl,
      'clone_url': instance.cloneUrl,
      'svn_url': instance.svnUrl.toString(),
      'forks': instance.forks,
      'open_issues': instance.openIssues,
      'watchers': instance.watchers,
      'topics': instance.topics,
      'mirror_url': instance.mirrorUrl?.toString(),
      'has_issues': instance.hasIssues,
      'has_projects': instance.hasProjects,
      'has_pages': instance.hasPages,
      'has_wiki': instance.hasWiki,
      'has_downloads': instance.hasDownloads,
      'has_discussions': instance.hasDiscussions,
      'archived': instance.archived,
      'disabled': instance.disabled,
      'visibility': instance.visibility,
      'license': instance.license,
      'permissions': instance.permissions,
      'text_matches': instance.textMatches,
      'temp_clone_token': instance.tempCloneToken,
      'allow_merge_commit': instance.allowMergeCommit,
      'allow_squash_merge': instance.allowSquashMerge,
      'allow_rebase_merge': instance.allowRebaseMerge,
      'allow_auto_merge': instance.allowAutoMerge,
      'delete_branch_on_merge': instance.deleteBranchOnMerge,
      'allow_forking': instance.allowForking,
      'is_template': instance.isTemplate,
      'web_commit_signoff': instance.webCommitSignoff,
    };
